# Generated by Django 4.2.18 on 2025-01-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phonebook', '0002_spamnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='spamnumber',
            name='spam_status',
            field=models.BooleanField(default=False),
        ),
    ]
