# Generated by Django 4.2.18 on 2025-01-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phonebook', '0003_spamnumber_spam_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spamnumber',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
